  language: "en-US"
  reviews:
    auto_review:
      enabled: true
      drafts: false
    tools:
      ruff:
        enabled: true
      ast-grep:
        essential_rules: true
        rule_dirs:
          - "custom_rules"
      pylint:
        enabled: true
  chat:
    auto_reply: true